#!/bin/bash
#
# Use with git-add-msg to log git commits to Trac using its XML-RPC API
#
# author: Heini Fagerlund
# version: 0.2.4
# license: MIT
#	
# The MIT License (MIT)
# [OSI Approved License]
# 
# The MIT License (MIT)
# 
# Copyright (c) Heini Fagerlund
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


#Trac configuration
. $currentDir/config.cfg

#populate result.xml with commit msg as comment
xsltproc --output bin/result.xml bin/transform.xsl bin/body_template.xml
  
if curl -H 'Content-Type: application/xml' --data @bin/result.xml "http://$username:$password@$host:$port/$instance/login/xmlrpc" &> /dev/null
  then printf "Trac ticket successfully updated.\n"
else
    printf "\t%s\n" "$bar" 
    printf "WARNING: Trac ticket could not be updated.\nAre the Trac settings in config.cfg up-to-date? 
If so, please check whether Trac is running, and try again.\n\nIf you are not using Trac, please disregard this message.\n\n"
    printf "\t%s\n" "$bar" 
fi
rm -r ./bin/
